# -*- coding: utf-8 -*-
"""BondDuration_File

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WpP8PsfAehyFVqD-_IqehNFll68BCYLe
"""

import numpy as np

def getBondDuration(y, face, couponRate, m, ppy=1):


    coupon = (couponRate * face) / ppy


    t = np.arange(1, m * ppy + 1) / ppy


    discount_factors = (1 + y / ppy) ** (-t * ppy)


    pv_coupons = coupon * discount_factors


    pv_face = face * discount_factors[-1]


    pv_total = np.sum(pv_coupons) + pv_face


    weighted_time = np.sum(t * pv_coupons) + t[-1] * pv_face


    duration = weighted_time / pv_total

    return round(duration, 2)


y = 0.03
face = 2000000
couponRate = 0.04
m = 10
ppy = 2

duration= getBondDuration(y, face, couponRate, m, ppy)
print(duration)