# -*- coding: utf-8 -*-
"""WhoAmI_File.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ItPbw0k3RYfdYxYjPmENT8iCL_sZ3KwR
"""

# Identify yourself for grading

def WhoAmI():
  return('zj2390')
print(WhoAmI())